services:
  test_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: test_frontend
    restart: always
    environment:
      -  APP_MODE=production #имитация запуска приложения в продакшн
    networks:
      - testNetwork
    ports:
      - 3001:3000

  test_backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: test_backend
    restart: always
    environment:
      - APP_ENV=staging
    env_file:
      - ./db-data/.env
    networks:
      - testNetwork
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: test_postgres_db
    restart: always
    env_file:
      - ./db-data/.env
    networks:
      - testNetwork

networks:
  testNetwork:
    driver: bridge
