services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    networks:
      - myNetwork
    environment:
      -  APP_MODE=production
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    environment:
      - APP_ENV=development
    env_file:
      - ./db-data/.env
    networks:
      - myNetwork
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - ./db-data/.env
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
