name: Test Application Deployment
on:
  push:
    branches: 
      -  master
jobs:
  deploy:
    runs-on: self-hosted  # Указываем использование self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: |
          docker compose down
          docker image prune -f
          docker container prune -f
          docker compose up --build -d
      
