name: Test Application Deployment
on:
  push:
    branches: 
      -  master
jobs:
  deploy:
    runs-on: self-hosted  # Указываем использование self-hosted runner

    steps:
      # Шаг 1: Проверяем код
      - name: Checkout repository
        run: |
          cd /opt
          git clone https://github.com/svintus1/test-app.git

      # Шаг 4: Запуск Docker Compose
      - name: Run Docker Compose
        run: |
          cd /opt
          docker compose down
          docker compose up --build -d
      
